version: '3.8'

services:
  frontend:

    depends_on:
      - backend

    build: ./frontend

    networks:
      - TG

    container_name: Frontend

    ports:
      - 5173:5173

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/bun.lockb
          action: rebuild
        - path: ./frontend/src
          target: /app/src
          action: sync
        - path: ./frontend/static
          target: /app/static
          action: sync

    restart: on-failure

    volumes:
      - frontend:/app

  backend:
    build: ./backend

    networks:
      - TG

    container_name: Backend

    ports:
      - 3000:3000

    env_file:
      - ./backend/.env

    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/bun.lockb
          action: rebuild
        - path: ./backend/src
          target: /app/src
          action: sync

    restart: on-failure

    volumes:
      - backend:/app

networks:
  TG:
    driver: bridge

volumes:
  frontend:
  backend:
